name       : libmirage
version    : 3.2.1
release    : 4
source     :
    - https://netcologne.dl.sourceforge.net/project/cdemu/libmirage/libmirage-3.2.1.tar.bz2 : e357160bbb15e967d7705f09bf7c43cac53aafc26b2171ccb5cc8c2ec7fb68f2
license    : GPL-2.0-or-later
component  : programming.library
summary    : CD-ROM image access library
description: |
    This is libMirage library, a CD-ROM image access library, and part of the
    userspace-cdemu suite, a free, GPL CD/DVD-ROM device emulator for linux. It is
    written in C and based on GLib.

    The aim of libMirage is to provide uniform access to the data stored in
    different image formats, by creating a representation of disc stored in image
    file, which is based on GObjects. There are various objects that represent
    different parts of the disc; disc, session, track, sector, etc. In addition to
    providing access to data provided by the image file, libMirage is also capable
    of generating some of the data that might not be present in image file. For
    instance, ISO image provides only user data from sector, without sync pattern,
    header, ECC/EDC codes or subchannel. When this missing data is requested,
    libMirage will transparently generate it.
builddeps  :
    - pkgconfig(liblzma)
    - pkgconfig(glib-2.0)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(zlib)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
